Breakpoint based stream debugger
Soarex16/intellij-community pull request #1
Opened 2022-04-12 07:59 UTC by Soarex16

Here be dragons (перед PR в идею надо написать подробное описание)

2022-04-17 18:22 UTC, bibaev requested changes
@Soarex16   Отличная работа!

2022-04-17 18:22 UTC, bibaev commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/MethodBreakpointFactoryImpl.kt
> +const val CONSUMER_INTERFACE_NAME = "java/util/function/Consumer"
```suggestion
private const val CONSUMER_INTERFACE_NAME = "java/util/function/Consumer"
```

2022-04-17 18:22 UTC, bibaev commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/MethodBreakpointTracer.kt
> +      valueContainer.dispose()
`dispose` можно взять из `finally`

2022-04-17 18:22 UTC, bibaev commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/MethodBreakpointTracer.kt
> +      LOG.error("Cannot create value of type ${e.type}", e)
Содержимое сообщений фактически переформатирует `errorMessage` исходных исключений. Вроде, можно ловить какой-нибудь базовый `BreakpontTracingException` передавать в `LOG.error(e)` как он есть.

2022-04-17 18:22 UTC, bibaev commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/StreamValuesCollectorImpl.kt
> +  private val valueContainers: MutableList<ObjectReference> = mutableListOf()
Выглядит немного запутано - есть поле `myValueContainer` + есть список `valueContainers`. К тому же, они различаются по типам. Может быть, оставим что-нибудь одно ?)

2022-04-17 18:22 UTC, bibaev commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/StreamValuesCollectorImpl.kt
> +class StreamValuesCollectorImpl(private val myValueContainer: ValueContainer) : StreamValuesCollector {
В Котлине нет конвенции добавлять к полям префикс `my
`

2022-04-17 18:22 UTC, bibaev commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/MethodSignature.kt
> +internal fun Method.methodSignature() = MethodSignature(
Напишу вкусовщину, так что можешь смело со мной не соглашаться :) Я бы использовал extension функции только в очень узком скоупе - чаще всего больше чем на уровне файла, то есть когда их декларация и использования в одном файле и их можно сделать private. Проблема таких extension функций в том, что они могут быть разбросаны по всему проекту и не всегда очевидно где их искать, а чтобы IDE помогла, нужно вызвать completion на объекте нужного типа, который, может быть и есть в контексте, но определение типа не содержит такой информации. 
В остальных случаях я бы использовал фабричные методы типа `MethodSignature.of(Method): MethodSignature`. Тогда, если разработчик видит, что какой-то API ожидает `MethodSignature`, то он просто снавигируется на него и сразу же увидит как его создать.

2022-04-17 18:22 UTC, bibaev commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/MethodBreakpointTracer.kt
> +  private fun trace(debugProcess: JavaDebugProcess, chain: StreamChain, callback: StreamExecutionCallback) {
Будет круто, если на вернем уровне этот метод будет состоять из максимально высокоуровневых шагов (очень упрощенно):
```kotlin
val locations = findBreakpointPlaces(...)
setBreakpoints(locations, ...)
val storage = createStorage(...)
executeStream(...)
callback.fillResults(storage,...)
```

2022-04-17 18:22 UTC, bibaev commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/MethodBreakpointTracer.kt
> +    val executionCallback = object : StreamExecutionCallback {
Анонимный класс получился довольно большой. Если вынести его в приватный вложенный класс, будет немного проще читать код :)

2022-04-17 18:22 UTC, bibaev commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/MethodBreakpointRequestor.kt
> +  val callback: MethodEntryCallback
private?

2022-04-17 18:22 UTC, bibaev commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/MethodBreakpointRequestor.kt
> +  override fun getSuspendPolicy(): String = DebuggerSettings.SUSPEND_ALL
Я бы добавил `TODO` на будущее, чтобы попробовать заменить policy на `SUSPEND_THREAD`. Вроде, нам потока вполне достаточно

2022-04-17 18:22 UTC, bibaev commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/MethodBreakpointRequestor.kt
> +      catch (e: Throwable) {
`Throwable` явно слишком широкий класс исключений, чтобы ловить и тем более, фактически игнорировать :) Давай заменим на `Exception` и пробрасывать дальше все исключения, за исключением некоторых, с которыми мы знаем что нужно делать

2022-04-17 22:51 UTC, Soarex16 commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/MethodBreakpointTracer.kt
> +      valueContainer.dispose()
Сначала об этом думал, но dispose нам делать надо только в случае, если вылетает исключение. Можно переделать на использование какого-нибудь флажка `val exceptionCaught: Bool`

2022-04-17 22:52 UTC, Soarex16 commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/StreamValuesCollectorImpl.kt
> +  private val valueContainers: MutableList<ObjectReference> = mutableListOf()
Да, с неймингом беды :)

2022-04-17 22:53 UTC, Soarex16 commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/StreamValuesCollectorImpl.kt
> +class StreamValuesCollectorImpl(private val myValueContainer: ValueContainer) : StreamValuesCollector {
Это замечательно, я так начал делать потому что в паре котлиновских классов такое увидел. Переделаю

2022-04-17 22:54 UTC, Soarex16 commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/MethodBreakpointTracer.kt
> +  private fun trace(debugProcess: JavaDebugProcess, chain: StreamChain, callback: StreamExecutionCallback) {
Да, мне не нравилось как этот метод написан, но не получалось сформулировать что именно не нравится

2022-04-17 22:55 UTC, Soarex16 commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/MethodBreakpointRequestor.kt
> +  override fun getSuspendPolicy(): String = DebuggerSettings.SUSPEND_ALL
С политиками я пока внимательно не разбирался, но это учту :)

2022-04-18 17:06 UTC, Soarex16 commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/MethodSignature.kt
> +internal fun Method.methodSignature() = MethodSignature(
Да, ты прав, переделаю в виде MethodSignature

2022-04-24 11:17 UTC, bibaev requested changes

2022-04-24 11:17 UTC, bibaev commented on plugins/stream-debugger/resources/classes/StreamDebuggerUtils.java.txt
> +class StreamDebuggerUtils {
Может все-таки будет сразу складывать скомпилированные `*.class` файлы в ресурсы. Вроде, в 100% случаев, байт-код, который мы в итоге получаем после компиляции будет одинаковый, а затраты времени на компиляцию и проблемы в случае нетривиальной конфигурации окружения скорее перевешивают профиты от компиляции "в полете".

2022-04-24 11:17 UTC, bibaev commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/DebuggerUtils.kt
> +  fun runInDebuggerThread(debugProcess: DebugProcessImpl, action: () -> Unit) {
Я думаю, что использование пободных методов приносит больше проблем, чем пользы. его исполнение зависит не от переданных параметров, а от окружающего состояния - потока, в котором происходит выполнение. В итоге, в одном случае action выполнится синхронно в том же потоке, в другом асинхронно в другом. В случае возникновения проблем это будет гораздо сложнее отдебажить, особенно, человеку, незнакомому с этим кодом. Лучше в каждый момент времени понимать, где именно происходит исполнение - на debugger потоке или нет. В таком случае, необходимости в подобных функциях не происходит :)

2022-04-24 11:17 UTC, bibaev commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/formatter/TraceFormatter.kt
> +interface TraceFormatter {
А может, лучше форматировать значения со стороны другой VM-ки? Работать с мапками напрямую всяко удобнее и быстрее.

2022-04-28 21:13 UTC, Soarex16 commented on plugins/stream-debugger/resources/classes/StreamDebuggerUtils.java.txt
> +class StreamDebuggerUtils {
Да, согласен, надо переделать)

2022-04-28 21:19 UTC, Soarex16 commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/DebuggerUtils.kt
> +  fun runInDebuggerThread(debugProcess: DebugProcessImpl, action: () -> Unit) {
Да, я уже успел столкнуться с багами асинхронщины)

2022-04-28 21:27 UTC, Soarex16 commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/formatter/TraceFormatter.kt
> +interface TraceFormatter {
Там есть хелпер код (plugins/stream-debugger/resources/classes/StreamDebuggerUtils.java.txt), который мапу раскладывает в ключи. Хотел сначала тоже делать чисто со стороны vm форматирование, но проблема в том, чтобы сделать это универсальным и расширяемым - тут я пока ничего не придумал

2022-04-29 13:16 UTC, bibaev requested changes

2022-04-29 13:16 UTC, bibaev commented on plugins/stream-debugger/src/com/intellij/debugger/streams/action/TraceStreamAction.java
> +    final BreakpointResolver breakpointResolver = new JavaBreakpointResolver(currentFile);
По-хорошему action не должен знания ничего про язык. Поэтому `JavaBreakpointResolver` надо бы возвращать из `provider` либо `LibrarySupport`

2022-04-29 13:16 UTC, bibaev commented on plugins/stream-debugger/src/com/intellij/debugger/streams/action/TraceStreamAction.java
> +    final StreamTracer tracer = new MethodBreakpointTracer(session, breakpointResolver, resultInterpreter);
Было бы удобно иметь возможность в полете переключиться на старый механизм. Например, чтобы сравнить получившиеся результаты

2022-04-29 13:16 UTC, bibaev commented on plugins/stream-debugger/src/com/intellij/debugger/streams/action/TraceStreamAction.java
> +    final StreamTracer tracer = new MethodBreakpointTracer(session, breakpointResolver, resultInterpreter);
Это можно сделат через значения registry

2022-04-29 13:16 UTC, bibaev commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/HelperClassUtils.kt
> +  fun compileClass(context: EvaluationContextImpl, resourceName: String, className: String): ClassObject? = javaClass
Это все еще нужно? Вроде теперь скомпилированные классы лежат в ресурсах :)

2022-04-29 20:05 UTC, Soarex16 commented on plugins/stream-debugger/src/com/intellij/debugger/streams/trace/breakpoint/HelperClassUtils.kt
> +  fun compileClass(context: EvaluationContextImpl, resourceName: String, className: String): ClassObject? = javaClass
Да, надо убрать

2022-04-29 21:31 UTC, Soarex16 commented on plugins/stream-debugger/src/com/intellij/debugger/streams/action/TraceStreamAction.java
> +    final BreakpointResolver breakpointResolver = new JavaBreakpointResolver(currentFile);
Это временно, пока не вынес поддержку в отдельный library support. Предлагаю это пока отложить, потому что пока нет стабильного набора точек расширения по языкам/библиотекам

2022-04-29 22:07 UTC, Soarex16 commented on plugins/stream-debugger/src/com/intellij/debugger/streams/action/TraceStreamAction.java
> +    final StreamTracer tracer = new MethodBreakpointTracer(session, breakpointResolver, resultInterpreter);
Сделано

2022-05-12 19:40 UTC, merged